### ISSUE TITLE
osprey does not work with express 4

### ISSUE THREAD

**Issue by cybertk** [mulesoft/osprey#63]
Given the following code which integrate osprey with express4. It returns `Cannot GET /api/xxx` for every path.

```js
var express = require('express');
var path = require('path');
var osprey = require('osprey');

var app = module.exports = express();

app.use(express.bodyParser());
app.use(express.methodOverride());
app.use(express.compress());
app.use(express.logger('dev'));

app.set('port', process.env.PORT || 3000);

api = osprey.create('/1', app, {
  ramlFile: path.join(__dirname, 'api.raml'),
  enableValidations: false,
  logLevel: 'debug'  //  logLevel: off->No logs | info->Show Osprey modules initializations | debug->Show all
});

if (!module.parent) {
  var port = app.get('port');
  app.listen(port);
  console.log('listening on port ' + port);
}
```

**Comment by blakeembrey** [comment]
Hi @cybertk, I've spent the last couple of weeks with a complete rewrite that'll work with any Express-compatible middleware. Feel free to check it, but it won't be available on `npm` yet since there's a couple of things still missing. But I'd love to hear feedback on whether it solves some of your needs :smile:

**Comment by jewelsjacobs** [comment]
@blakeembrey I'd love to get my hands on this rewrite too . . .

**Comment by blakeembrey** [comment]
@jewelsjacobs At the moment it's only installable from git, so you should be able to do `npm install mulesoft/osprey`. I can look at tagging an alpha release tomorrow if you're interested :+1:

**Comment by jewelsjacobs** [comment]
awesome!  thanks so much!

**Comment by jewelsjacobs** [comment]
eh hate to bug you again @blakeembrey but I can't seem to get the new version of osprey to work with api-designer.

I used to have this:

```javascript
api = osprey.create('/api', app, {
  ramlFile: path.join(__dirname, '/dist/assets/api.raml'),
  logLevel: 'debug',  //  logLevel: off->No logs | info->Show Osprey modules initializations | debug->Show all
  enableMocks: true
  });
``` 

I'm trying to figure out how to use the sample you provide in the REAME but not having much luck. :(

**Comment by blakeembrey** [comment]
@jewelsjacobs Would you mind creating a new issue with the error or something you've received? There isn't currently a mocking service yet, but it'd be easy to add example responses if that's your issue.

**Comment by jewelsjacobs** [comment]
@blakeembrey thats exactly what I'm looking for.  The ability to mock out the example responses from the api designer.

**Comment by blakeembrey** [comment]
@jewelsjacobs Was that your issue or was it technical? I can push a module for this at the end of the week, but I was disputing whether it should be a separate module (doesn't seem like core functionality to me). For example, you would just do `ospreyExampleServer(raml)` instead of creating the same type with an option.

**Comment by jewelsjacobs** [comment]
@blakeembrey this is probably better as a separate module.  I probably have to hack it out on my own.

Its a little difficult as I'm saving the assets to a mongodb as opposed to a folder on the server.

You can see what I'm doing in my repo here although I'm updating this in a major way (https://github.com/jewelsjacobs/raml-osprey-api-designer/blob/master/routes/files.js).  I'm trying to combine api-designer with osprey to have mock data suite for front end devs.  

With this setup I actually have to save the file both to the mobgodb db and then to the folder on the server (which I still have to hack out because now I'm just doing it manually).

That repo is an old version.  The new version will have the latest version of api-designer unbuilt with the back end upgraded to use Express v4+

But basically what I'm trying to do is  generate mock data from the example responses without messing up the calls to the api console (which was working before Express v4).

**Comment by blakeembrey** [comment]
Ok, I'll look at publishing the examples module for you to review the implementation but the issue of having to both write and save to mongodb shouldn't exist anymore. I'm accepting the parsed object, so you should just be able to override the file reader of the `raml-parser` to instead read from mongodb. Then just pass that object to Osprey 2.

**Comment by jewelsjacobs** [comment]
@blakeembrey I updated my repo with the latest of what I have: https://github.com/jewelsjacobs/raml-osprey-api-designer

It should give you a better idea of what I'm doing.  I'm saving the files to the db and folder now successfully (code in repo does this) but I can also read from mongodb as well.

The code in the repo with the npm module version of osprey (not the github `npm install mulesoft/osprey` version) - https://github.com/jewelsjacobs/raml-osprey-api-designer/blob/master/server.js#L53-57 will result in:

```
127.0.0.1 - - [03/Mar/2015:17:28:45 +0000] "GET /api/console/scripts/app.js HTTP/1.1" 304 - "http://localhost:8081/api/console" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36"

/Users/jewelsjacobs/WebstormProjects/api-designer/node_modules/osprey/dist/osprey.js:78
            data = data.toString().replace(/^baseUri:.*$/gmi, "baseUri: " + ap
                        ^
TypeError: Cannot call method 'toString' of undefined
    at /Users/jewelsjacobs/WebstormProjects/api-designer/node_modules/osprey/dist/osprey.js:78:25
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)
```

I'm still not exactly sure how to get the latest version to do the same thing without the error but it sounds like you are going to provide something.

Let me know if there is anything I can do to assist.

**Comment by jewelsjacobs** [comment]
Oh I guess I have to always name my file api.raml with this setup :)

**Comment by blakeembrey** [comment]
@jewelsjacobs That error is not from my code, it's the old Osprey version. Not sure what you're asking, but I am going to build the example server (probably next week). You shouldn't need to use `api.raml` as the filename either. In fact, the new Osprey version doesn't even read files.
