### ISSUE TITLE
Cannot find module 'router/engine' error from osprey-router

### ISSUE THREAD

**Issue by jewelsjacobs** [mulesoft/osprey#64]
There's an osprey-router error that crashes `osprey@0.2.0-alpha node_modules/osprey` when running with expressJS v4+ and latest version of nodeJS

Here are the details:
https://github.com/mulesoft-labs/osprey-router/issues/1

Thanks for all of your hard work with this!

**Comment by blakeembrey** [comment]
@jewelsjacobs Yeah, that dependency should be loading from git but I guess it keep loading from an internal cache instead because it's the same version. The only fix I can think of right now is manually linking, at least until `router` is released with engine support (https://github.com/pillarjs/router/pull/13).

**Comment by dougwilson** [comment]
Just run

    npm cache clean

Then reinstall your dependencies and it should pull for the git fork. And yes, I believe it's because the fork has the same version number and npm's cache is confused.

**Comment by jewelsjacobs** [comment]
@blakeembrey sorry to bug you folks with this but I'm not sure what and where I should be manually linking as a temp workaround for this.

Can you please clarify?

**Comment by jewelsjacobs** [comment]
I solved the mystery as to why your router branch with engine support was not working @blakeembrey:

https://github.com/blakeembrey/router/pull/1

**Comment by blakeembrey** [comment]
Wow, thanks! Sorry I missed that :+1:
