### ISSUE TITLE
Error after mounting notFoundHandler when using Osprey from different RAML files

### ISSUE THREAD

**Issue by alleypa** [mulesoft/osprey#83]
Hello @blakeembrey 

I get the blow error when I make a request. This also happens after all the middleware handlers are mounted. Please let know if it helps.

Error: Path /casehearing/3 was not found in the RAML file for this application
   at notFoundHandler (E:\GIT\MOJ\ccsfe-raml-server\node_modules\osprey\lib\server.js:61:23)
   at Layer.handle [as handle_request] (E:\GIT\MOJ\ccsfe-raml-server\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (E:\GIT\MOJ\ccsfe-raml-server\node_modules\express\lib\router\index.js:312:13)
   at E:\GIT\MOJ\ccsfe-raml-server\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (E:\GIT\MOJ\ccsfe-raml-server\node_modules\express\lib\router\index.js:330:12)
   at next (E:\GIT\MOJ\ccsfe-raml-server\node_modules\express\lib\router\index.js:271:10)
   at Layer.handle [as handle_request] (E:\GIT\MOJ\ccsfe-raml-server\node_modules\express\lib\router\layer.js:91:12)

**Comment by blakeembrey** [comment]
Can you share some sample code to reproduce it? The `notFoundHandler` needs to be mounted _after_ the middleware handlers are mounted, otherwise everything will be considered not found.

**Comment by alleypa** [comment]
Hi @blakeembrey 
Please checkout this repo https://github.com/alleypa/ramlserverpoc. The entry file is serverOS1.js. You can see the endpoints seperated into read and write folders. Presently the implementation works returning the expected json once the correct url is requested. But once I mount the notFoundHandler, I get the above error. Please let me know if I should give more information to diagnose this

**Comment by blakeembrey** [comment]
Your issue is that `osprey.loadFile` is asynchronous, but you're mounting the not found handler synchronously. You actually have the same bug with your logger and error handler and your listener, basically anything happening after the Osprey calls. I would recommend having your two endpoints export the routers themselves, then move the osprey loads into the core file. Here's some psuedo code:

```js
Promise.all([
  osprey.loadFile('foo.raml'),
  osprey.loadFile('bar.raml')
]).then(function (middlewares) {
  app.use(middlewares[0], middlewares[1])
  app.use(logger('dev'));
  app.use(errorHandler.init);
  app.use(osprey.server.notFoundHandler);

  app.listen(config.scheduling.port, function () {
    console.log('The CSSAPI Raml mock server is running at ' + host + config.scheduling.port);
  });
})
```

This is just a pitfall of asynchronous program you need to be aware of. Currently your `.listen` will actually be listening before the Osprey and the routers are even ready, so it's possible requests would 404 until those mount right now.

**Comment by alleypa** [comment]
Hi @blakeembrey 

Many thanks for your suggestion. The approach did work.

Regards
Olu

**Comment by blakeembrey** [comment]
Perfect, I'll close this issue now.
